routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
//PAYPAL
Route::get('paypal/success', 'PaypalController@success')->name('paypal.success');
Route::get('paypal/cancel', 'PaypalController@cancel')->name('paypal.cancel');

Route::get('/', 'HomeController@index')->name('home');
Route::get('category/{categorySlug}', 'ProductController@list')->name('product.list');
Route::get('search', 'ProductController@search')->name('search');
Route::get('my-company/{slug}', 'HomeController@myCompany')->name('my-company');
Route::get('contact', 'HomeController@contact')->name('contact');
Route::post('send-contact', 'HomeController@sendContact')->name('contact.post');

Route::group(['prefix' => 'cart', 'as' => 'cart'], function () {
    Route::get('/', 'CartController@cart');
    Route::get('checkout', 'CartController@checkout')->name('.checkout');
    Route::post('post-checkout', 'CartController@checkoutPost')->name('.checkout.post');
    Route::get('checkout-success', 'CartController@checkoutSuccess')->name('.checkout.success');
    Route::post('add-cart', 'CartController@add')->name('.add');
    Route::post('update', 'CartController@update')->name('.update');
	Route::get('remove/{rowId}', 'CartController@remove')->name('.remove');
	
	Route::post('validate-address-id', "CartController@validateAddressId")->name('.validate-address-id');
	Route::post('validate-address', "CartController@validateAddress")->name('.validate-address');
});

Route::group(['prefix' => 'user', 'as' => 'user', 'middleware' => 'auth'], function () {
    Route::get('my-account', 'UserController@account')->name('.account');
    Route::get('profile', 'UserController@profile')->name('.profile');
    Route::post('profile-update', 'UserController@profileUpdate')->name('.profile.update');
	Route::get('addresses', 'UserController@addresses')->name('.addresses');
	
	Route::match(['post', 'get'], 'address-add', 'UserController@addressAdd')->name('.addresses.add');
	Route::match(['post', 'get'], 'address-update/{address_id}', 'UserController@adressUpdate')->name('.addresses.update');
	Route::get('address-delete', 'UserController@addressDelete')->name('.addresses.delete');
	
    Route::get('order-history', 'UserController@orderHistory')->name('.order-history');
});

Route::get('mail', 'CartController@mail');

Route::group(['prefix' => 'coupon'], function () {
    Route::post('apply', 'CouponController@apply')->name('coupon.apply');
    Route::post('destroy', 'CouponController@destroy')->name('coupon.destroy');
});

Route::group(['prefix' => 'news'], function () {
    Route::get('/', 'NewsController@list')->name('news');
    Route::get('{slug}', 'NewsController@detail')->name('news.detail');
});

Route::group(['prefix' => 'admin'], function () {
	Route::get('customers', 'Voyager\VoyagerUserController@customer');
    Voyager::routes();
});

Auth::routes(['verify' => true]);

Route::group(['prefix' => 'fedex'], function () {
    Route::get('check-rate', 'FedEx\RateRequestController@checkRate');
    Route::get('validate', 'FedEx\ValidateAddressController@handle');
	Route::post('track', 'FedEx\TrackController@trackById');
});

Route::group(['prefix' => 'excel'], function () {
    Route::get('import-view', 'ImportController@importView')->name('import.view');
    Route::post('import-product', 'ImportController@product')->name('import.product');
    Route::post('import-stock', 'ImportController@stock')->name('import.stock');
});

Route::get('{slug}', 'ProductController@detail')->name('product.detail'); //always bottom

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Support\Facades\Auth;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends \TCG\Voyager\Models\User implements MustVerifyEmail
{
    use Notifiable;

	protected $with = ['addresses'];
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    // protected $fillable = [
    //     'name', 'email', 'password',
	// ];
	protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
	];
	
	public function addresses()
	{
		return $this->hasMany('App\Models\Address', 'user_id', 'id');
	}

	public function getFullnameAttribute()
	{
		return "{$this->first_name} {$this->last_name}";
	}

	public function scopeRoleNotNull(Builder $query)
	{
		return $query->whereNotNull('role_id')->where('role_id', '>=', Auth::user()->role_id);
	}
}

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use App\Events\CheckoutSuccessEvent;
use App\Http\Controllers\FedEx\RateRequestController;
use App\Http\Controllers\FedEx\ValidateAddressController;
use App\Models\Address;
use App\Models\OrderInformation;
use App\Models\Product;
use App\Models\ProductDetail;
use App\Models\UserCoupon;
use App\Traits\MailCheck;
use App\Traits\SEO;
use App\Traits\UnitConversion;
use Gloudemans\Shoppingcart\Facades\Cart;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CartController extends Controller
{
    use SEO, MailCheck, UnitConversion;

    protected function findInCart($productDetail)
    {
        return Cart::search(function ($itemCart) use ($productDetail) {
            return $itemCart->id == $productDetail->id;
        })->first();
    }

    /* AJAX */
    public function add(Request $request)
    {
        $productId = $request->product_id;
        $colorId   = $request->options['color'];
        $sizeId    = $request->options['size'];

        $product = Product::findOrFail($productId);

        $productDetail = $product->productDetail->filter(function ($item) use ($colorId, $sizeId) {
            return $item->color_id == $colorId and $item->size_id == $sizeId;
        })->first();

        if (!$productDetail) {
            abort(404);
        }

        $matchItemCart = $this->findInCart($productDetail);

        if ($matchItemCart):
            Cart::update($matchItemCart->rowId, $matchItemCart->qty + $request->qty);
        else:
            $options = array_merge(
                $request->options,
                [
                    'slug'  => $product->slug,
                    'image' => $product->thumbnail('cropped'),
                    'color' => $productDetail->color->name,
                    'size'  => $productDetail->size->name,
                    'weight' => $product->weight ?? 1000,
                    'isFreeShipping'  => $product->is_free_shipping,
                ]
            );
            Cart::add($productDetail, $request->qty, $options);
        endif;

        return [
            'status' => 'success',
            'cart'   => Cart::content(),
        ];
    }

    public function remove(Request $request)
    {
        Cart::remove($request->rowId);

        return redirect()->back();
    }

    public function update(Request $request)
    {
        $qty = $request['product-quantity-spin'];
        Cart::update($request->rowId, $qty);

        return redirect()->back();
    }

    public function cart(): View
    {
        $seoMeta = [
            'seo_title'        => 'Cart',
            'meta_description' => 'Cart list',
            'meta_keywords'    => 'cart, list',
            'meta_image_fb'    => '',
        ];
        $data = array_merge(compact('seoMeta'), $this->getCartNumbers());

        return view('cart.list')->with($data);
    }

    public function checkout()
    {
        if (!Cart::count()):
            return redirect()->route('home');
        endif;

        $seoMeta = [
            'seo_title'        => 'Checkout',
            'meta_description' => 'Cart page',
            'meta_keywords'    => 'checkout, payment',
            'meta_image_fb'    => '',
        ];
        $data = array_merge(compact('seoMeta'), $this->getCartNumbers());

        return view('cart.checkout')->with($data);
    }

    public function checkoutPost(Request $request)
    {
        if (Cart::content()->isNotEmpty()):
            $cartNumbers = $this->getCartNumbers();

            if ($request->address_id and Auth::check()):
                $addressData = $this->addressData($request->address_id);

                $data = [
                    'name'                   => "{$addressData['first_name']} {$addressData['last_name']}",
                    'email'                  => $request->email,
                    'phone'                  => $addressData['phone'],
                    'address'                => $addressData['address'],
                    'city'                   => $addressData['city'],
                    'state_or_province_code' => $addressData['state_or_province_code'],
                    'postal_code'            => $addressData['postal_code'],
                    'delivery_message'       => $request->delivery_message,
                    'payment_method'         => $request->payment_method ?? 'bank',
                ];
            else:
                $request->validate([
                    'first_name'      => 'required',
                    'last_name'       => 'required',
                    'email'           => 'required|email',
                    'phone'           => 'required',
                    'address'         => 'required',
                    'city'            => 'required',
                    'postal_code'     => 'required|integer',
                    'delivery_method' => 'required',
                ]);

                $data = [
                    'name'                   => "{$request->first_name} {$request->last_name}",
                    'email'                  => $request->email,
                    'phone'                  => $request->phone,
                    'address'                => $request->address,
                    'city'                   => $request->city,
                    'state_or_province_code' => $request->state_or_province_code,
                    'postal_code'            => $request->postal_code,
                    'delivery_message'       => $request->delivery_message,
                    'payment_method'         => $request->payment_method ?? 'bank',
                ];
            endif;

            $data = array_merge($data, [
                'tax'          => $cartNumbers['tax'],
                'discount'     => $cartNumbers['discount'],
                'coupon'       => $cartNumbers['coupon'],
                'delivery_fee' => $cartNumbers['deliveryFee'],
                'sub_total'    => $cartNumbers['newSubtotal'],
                'total'        => $cartNumbers['newTotal'],
                'data'         => $request->data,
                'transaction_id'=>$request->transaction_id
            ]);

            //create default address for Login user
            if (Auth::check() and Auth::user()->addresses->isEmpty()):
                Auth::user()->addresses()->create($request->all());
            endif;

            //save coupon+user
            $cartNumbers['coupon'] && $cartNumbers['is_one_time'] ? $this->saveUserCoupon($cartNumbers['id']) : '';

            //persist Order details
            $orderInfo = $this->persistOrder($data);

            Cart::destroy();
            session()->forget('coupon');
            session()->forget('deliveryFee');

            //send email customer,send email admin...
            event(new CheckoutSuccessEvent($orderInfo));

            $seoMeta = [
                'seo_title'        => 'Cart',
                'meta_description' => 'Cart list',
                'meta_keywords'    => 'cart, list',
                'meta_image_fb'    => '',
            ];

            return view('cart.checkout-success', compact('orderInfo'));
        endif;

        return redirect()->route('home');
    }

    public function addressData($addressId)
    {
        $address = Address::where('user_id', \Auth::id())->where('id', $addressId)->firstOrFail();

        return [
            'first_name'             => $address->first_name,
            'last_name'              => $address->last_name,
            'phone'                  => $address->phone,
            'address'                => $address->address,
            'city'                   => $address->city,
            'state_or_province_code' => $address->state_or_province_code,
            'postal_code'            => $address->postal_code,
        ];
    }

    public function persistOrder($data)
    {
        return \DB::transaction(function () use ($data) {
            $orderInfo = OrderInformation::create($data);

            foreach (Cart::content() as $item) {
                $orderInfo->order()->create([
                    'product_detail_id' => $item->id,
                    'quantity'          => $item->qty,
                    'price'             => $item->price,
                    'product_name'      => $item->name,
                    'product_color'     => $item->options->color,
                    'product_size'      => $item->options->size,
                    'product_image'     => $item->options->image,
                ]);

                //minus qty in Product_detail
                $this->updateProductDetailQuantity($item);
            }

            return $orderInfo;
        });
    }

    protected function getCartNumbers(): array
    {
        $tax         = $this->stringToFloat(Cart::tax()) / 100;
        $discount    = session()->get('coupon')['discount'] ?? 0;
        $newSubtotal = $this->stringToFloat(Cart::subtotal()) - $discount;
        $deliveryFee = (float) session()->get('deliveryFee');

        $newTotal    = $newSubtotal * (1 + $tax) + $deliveryFee;
        $coupon      = session()->get('coupon')['name'] ?? null;
        $id          = session()->get('coupon')['id'] ?? null;
        $is_one_time = session()->get('coupon')['is_one_time'] ?? null;

        return compact('tax', 'discount', 'deliveryFee', 'newSubtotal', 'newTotal', 'coupon', 'id', 'is_one_time');
    }

    protected function saveUserCoupon(Int $couponId): void
    {
        UserCoupon::insert([
            'user_id'   => Auth::id(),
            'coupon_id' => $couponId,
        ]);
    }

    protected function updateProductDetailQuantity($item): void
    {
        $productDetail = ProductDetail::find($item->id);
        $productDetail->quantity -= $item->qty;
        $productDetail->save();
    }

    public function validateAddress(Request $request)
    {
        $request->validate([

resources/views/cart/form/step-1.blade.php
<section class="checkout-step -current js-current-step">
	<h1 class="step-title h3">
		<i class="material-icons done"></i>
		<span class="step-number">1</span>
		Personal Information
	</h1>

	<div class="content">
		<ul class="nav nav-inline my-2" role="tablist">
			@auth
				<p class="identity">
					Connected as <a href="{{route('user.profile')}}">{{Auth::user()->fullname}}</a>.
				</p>
				<p>
					Not you? <a href="{{route('logout')}}" onclick="event.preventDefault();
					document.getElementById('logout-form').submit();">Log out</a>
				</p>
				<p><small>If you log out now, your cart will be emptied.</small></p>
				<input name="first_name" type="hidden" value="{{Auth::user()->first_name}}">
				<input name="last_name" type="hidden" value="{{Auth::user()->last_name}}" >
				<input name="email" type="hidden" value="{{Auth::user()->email}}" >
			@else
				<li class="nav-item">
					<a class="nav-link active" data-toggle="tab" href="#checkout-guest-form" role="tab"
						aria-controls="checkout-guest-form" aria-selected="true">
						Order as a guest
					</a>
				</li>
			@endauth
		</ul>

		@guest
		<div class="tab-content">
			<div class="tab-pane active" role="tabpanel" id="registerForm">

				<section>
					<div class="form-group row ">
						<label class="col-md-3 form-control-label">Social title</label>
						<div class="col-md-6 form-control-valign">
							<label class="radio-inline">
								<span class="custom-radio">
									<input name="gender" type="radio" value="1" checked>
									<span></span>
								</span>
								Mr.
							</label>
							<label class="radio-inline">
								<span class="custom-radio">
									<input name="gender" type="radio" value="2">
									<span></span>
								</span>
								Mrs.
							</label>
						</div>
					</div>

					<div class="form-group row ">
						<label class="col-md-3 form-control-label required">First name</label>
						<div class="col-md-6">
							<input class="form-control" name="first_name" type="text" value="{{Auth::user()->first_name ?? ''}}" required>
						</div>
						<div class="col-md-3 form-control-comment">
						</div>
					</div>

					<div class="form-group row ">
						<label class="col-md-3 form-control-label required">Last name</label>
						<div class="col-md-6">
							<input class="form-control" name="last_name" type="text" value="{{Auth::user()->last_name ?? ''}}" required>
						</div>
						<div class="col-md-3 form-control-comment">
						</div>
					</div>

					<div class="form-group row ">
						<label class="col-md-3 form-control-label required">Email</label>
						<div class="col-md-6">
							<input class="form-control" name="email" type="email" value="{{Auth::user()->email ?? ''}}"
								required />
						</div>
						<div class="col-md-3 form-control-comment"></div>
					</div>
				</section>
			</div>
		</div>
		@endguest
	</div>
</section>

resources/views/cart/form/step-2.blade.php
<section class="checkout-step -current js-current-step">
	<h1 class="step-title h3">
		<i class="material-icons done"></i>
		<span class="step-number">2</span>
		Addresses
	</h1>

	<div class="content">
		<div class="js-address-form">
			<p>The selected address will be used both as your personal address (for invoice) and as your
				delivery address.</p>
			<div id="delivery-address" class="js-address-form row" style="display:flex; flex-wrap: wrap;">
				@if(Auth::check() and Auth::user()->addresses->isNotEmpty())

					@foreach (Auth::user()->addresses as $address)
						<article class="address-item selected col-sm-4" onclick="resetShippingMethod();" id="id-address-delivery-address-{{$address->id}}">
							<header class="h4">
								<label class="radio-block">
									<span class="custom-radio">
										<input type="radio" name="address_id" value="{{$address->id}}"
											{{$loop->index == 0 ? 'checked' : ''}}>
										<span></span>
									</span>
									<span class="address-alias h4">{{$address->fullname}}</span>
									<div class="address">{{$address->company}}<br>{{$address->address}}<br>{{$address->city}}
										{{$address->postal_code}}<br>{{$address->phone}}</div>
								</label>
							</header>
						</article>
					@endforeach
					<script>
						var resetShippingMethod = function(){
							$('#delivery_fedex').prop('checked', false);
							$('#step-4').addClass('invisible');
						}
					</script>
					<p class="add-address row">
						<a href="{{route('user.addresses.add')}}"> <i class="material-icons"></i>add new address</a>
					</p>
				@else
					<section class="form-fields" style="width:100%;">
						<div class="form-group row ">
							<label class="col-md-3 form-control-label required">
								Address
							</label>
							<div class="col-md-6">
								<input class="form-control" name="address" id="address" type="text" value="" maxlength="128" required="">
							</div>

							<div class="col-md-3 form-control-comment">
							</div>
						</div>

						<div class="form-group row ">
							<label class="col-md-3 form-control-label required">
								City
							</label>
							<div class="col-md-6">
								<input class="form-control" name="city" id="city" type="text" value="" maxlength="64" required="">
							</div>
						</div>

						<div class="form-group row ">
							<label class="col-md-3 form-control-label required">
								State Or Province Code
							</label>
							<div class="col-md-6">
								<input class="form-control" name="state_or_province_code" id="state_or_province_code" type="text" value="" maxlength="64" required="">
							</div>
						</div>

						<div class="form-group row ">
							<label class="col-md-3 form-control-label required">
								Zip/Postal Code
							</label>
							<div class="col-md-6">
								<input class="form-control" name="postal_code" id="postal_code" type="text" value="" maxlength="12"
									required="">
							</div>

							<div class="col-md-3 form-control-comment">
							</div>
						</div>

						<div class="form-group row ">
							<label class="col-md-3 form-control-label">
								Phone
							</label>
							<div class="col-md-6">
								<input class="form-control" name="phone" type="text" value="" maxlength="32">
							</div>

							<div class="col-md-3 form-control-comment">
								Optional
							</div>
						</div>
					</section>
				@endauth
			</div>
		</div>

	</div>
</section>

resources/views/cart/form/step-3.blade.php
<section id="checkout-delivery-step" class="checkout-step -current -reachable js-current-step">
	<h1 class="step-title h3">
		<i class="material-icons done"></i>
		<span class="step-number">3</span>
		Shipping Method
	</h1>

	<div class="content">
		<div class="errors">

		</div>
		<div class="delivery-options-list">
			<div class="form-fields">
				<div class="delivery-options">
					<div class="row delivery-option">
						<div class="col-sm-1">
							<span class="custom-radio float-xs-left required">
								<input type="radio" name="delivery_method" id="delivery_fedex" value="1" required>
								<span></span>
							</span>
						</div>
						<label for="delivery_option_2" class="col-sm-11 delivery-option-2">
							<div class="row">
								<div class="col-sm-5 col-xs-12">
									<div class="row">
										<div class="col-xs-3">
											<img src="{{asset("img/shipping.jpg")}}" alt="My carrier">
										</div>
										<div class="col-xs-9">
											<span class="h6 carrier-name">FedEx Ground</span>
										</div>
									</div>
								</div>
								<div class="col-sm-4 col-xs-12">
									<span class="carrier-delay" style="display:none;">
										Processing data...
										<img src="{{asset('img/loader.gif')}}" alt="" width="80">
									</span>
								</div>
								<div class="col-sm-3 col-xs-12">
									USD <span class="carrier-price">{{number_format($deliveryFee, 2)}}</span>
								</div>
							</div>
						</label>
					</div>
					<div class="clearfix"></div>
				</div>

				<div class="order-options">
					<div id="delivery">
						<label for="delivery_message">If you would like to add a comment about your order, please write it in the field below.</label>
						<textarea rows="3" cols="120" name="delivery_message"></textarea>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<script>
	$('#delivery_fedex').on('click',function(){
		$('.errors').empty();
		if($('input[name="address_id"]').length > 0){
			//auth
			let address_id = $('input[name="address_id"]:checked').val(),
				_token = $('input[name="_token"]').val();
			$('.carrier-delay').css('display', 'inline-block');
			$.post('/cart/validate-address-id', {address_id, _token})
				.done(function(response){
					// console.log(response);

					const deliveryFee = parseFloat(response.deliveryFee);
					$('.carrier-price').text(deliveryFee);
					$('.cart-total .total-value').text(response.newTotal);
					$('input[name="total-value"]').val(response.newTotal);
					$('.carrier-delay').css('display', 'none');
					$('#step-4').removeClass('invisible');
				})
				.fail(function(errors){
					const message = `${errors.responseJSON.message} Please use correct address`;
					$('.errors').html(`<div class="alert alert-warning">${message}</div>`);
					$('#delivery_fedex').attr('checked', false).trigger('change');
					$('.carrier-delay').css('display', 'none');
				})
		} else {
			//guest
			let addressData = $('#checkout-form').serialize();console.log(addressData)
			$('.carrier-delay').css('display', 'inline-block');
			$.post('/cart/validate-address', addressData)
				.done(function(response){
					// console.log(response);

					const deliveryFee = parseFloat(response.deliveryFee);
					$('.carrier-price').text(deliveryFee);
					$('.cart-total .total-value').text(response.newTotal);
					$('input[name="total-value"]').val(response.newTotal);
					$('.carrier-delay').css('display', 'none');
					$('#step-4').removeClass('invisible');
				})
				.fail(function(errors){
					const message = `${errors.responseJSON.message} Please use correct address`;
					$('.errors').html(`<div class="alert alert-warning">${message}</div>`);
					$('#delivery_fedex').attr('checked', false).trigger('change');
					$('.carrier-delay').css('display', 'none');
				})
		}
	})
</script>

resources/views/cart/form/step-4.blade.php
<section id="step-4" class="checkout-step -current -reachable js-current-step invisible">
	<h1 class="step-title h3">
		<i class="material-icons done"></i>
		<span class="step-number">4</span>
		Payment
	</h1>

	<div class="content">
		<div class="payment-options ">
			{{-- Pay by bank wire --}}
			<div>
				<div class="payment-option clearfix">
					<span class="custom-radio float-xs-left">
						<input class="ps-shown-by-js " id="payment-option-1" name="payment_method" value="bank" type="radio" required>
						<span></span>
					</span>

					<label for="payment-option-1">
						<span>Pay by bank wire</span>
					</label>
				</div>
			</div>

			<div id="payment-option-1-additional-information" class="js-additional-information definition-list additional-information">
				<section>
					<p>
						Please transfer the invoice amount to our bank account. You will receive our order
						confirmation by email containing bank details and order number.
						Goods will be reserved 7 days for you and we'll process the order immediately after
						receiving the payment.
					</p>
					<p>Payment is made by transfer of the invoice amount to the following account:</p>

					<dl>
						<dt>Amount</dt>
						<dd class="cart-total">USD <span class="total-value">{{number_format($newTotal, 2)}}</span> (tax incl.)</dd>
						<dt>Bank name</dt>
						<dd>{{setting('bank.name') ?? '___________'}}</dd>
						<dt>Name of account owner</dt>
						<dd>{{setting('bank.owner') ?? '___________'}}</dd>
						<dt>Please include these details</dt>
						<dd>{{setting('bank.note') ?? '___________'}}</dd>

					</dl>
					<p>
						<div class="ps-shown-by-js" style="text-align:center;">
							<button type="submit" class="btn btn-primary center-block place-your-order">
								Place your order
							</button>
						</div>
					</p>
				</section>
			</div>
			{{-- ./Pay by bank wire --}}

			{{-- Paypal --}}
			<div>
				<div id="payment-option-2-container" class="payment-option clearfix">
					<span class="custom-radio float-xs-left">
						<input class="ps-shown-by-js " id="payment-option-2" name="payment_method" value="paypal" type="radio" required="">
						<span></span>
					</span>

					<label for="payment-option-2">
						<span>Paypal</span>
					</label>

				</div>
			</div>
			<div id="payment-option-2-additional-information" class="js-additional-information definition-list additional-information ps-hidden ">
				<section>
					<div id="paypal-button-container"></div>

					<!-- Include the PayPal JavaScript SDK -->
					<script
						src="https://www.paypal.com/sdk/js?client-id=AX5c44JpPyyLqNGP5-F6gv7QK2TSstiqq__XmTRla_CBjXvvMq_xQmuC82mf1ZtlDkxMyQmHCn4cpVdb&currency=USD">
					</script>

					<script>
						// Render the PayPal button into #paypal-button-container
						paypal.Buttons({
							onInit: function(data, actions) {
								// Disable the buttons
								actions.disable();
	
								document.querySelector('#delivery_fedex')
									.addEventListener('change', function(event) {
										if (event.target.checked) {
											actions.enable();
										} else {
											actions.disable();
										}
									});
							},
							// onClick is called when the button is clicked
							onClick: function(data, actions) {
								let firstName = $('input[name="first_name"]').val(),
									lastName = $('input[name="last_name"]').val(),
									email = $('input[name="email"]').val(),
									address = $('#address').val(),
									city = $('#city').val(),
									state_or_province_code = $('#state_or_province_code').val(),
									postal_code = $('#postal_code').val(),
									delivery_method = $('#delivery_fedex').is(':checked');
								if($('input[name="address_id"]').length > 0){
									return actions.resolve();
								}else {
									if (!firstName || !lastName || !email || !address || !city || !state_or_province_code || !postal_code || !postal_code) {
										$.notify('Please fill in all fields', 'error');
										return actions.reject();
									} else {
										return actions.resolve();
									}
								}
							},
							// Set up the transaction
							createOrder: function(data, actions) {
								return actions.order.create({
									purchase_units: [{
										amount: {
											value: $('input[name="total-value"]').val()
										}
									}]
								});
							},
							// Finalize the transaction
							onApprove: function(data, actions) {
								return actions.order.capture().then(function(details) {
									// Show a success message to the buyer
									alert(`Transaction completed by ${details.payer.name.given_name}!`);
									$('#data-response').val(JSON.stringify(details));
									if(details.status == "COMPLETED"){
										$('#data-transaction-id').val(details.purchase_units[0].payments.captures[0].id);
									}
									$('#step-4').addClass('invisible');
									$('#checkout-form').submit();
								});
							}
						}).render('#paypal-button-container');
					</script>
				</section>
			</div>
			{{-- ./Paypal --}}
		</div>

		{{-- <div id="payment-confirmation">
			<div class="ps-shown-by-js">
				<button type="submit" class="btn btn-primary center-block place-your-order">
					Place your order
				</button>
			</div>
		</div> --}}
	</div>
</section>